---
driver:
  name: openstack
  flavor_ref: 'm1.large'
provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  attributes:
    openstack:
      server_root_password: rootpass
      forbid_remote_root: false
      secret:
        key_path: /tmp/kitchen/encrypted_data_bag_secret
    yum:
      epel:
        baseurl: http://epel.osuosl.org/7/$basearch
        gpgkey: http://epel.osuosl.org/RPM-GPG-KEY-EPEL-7

suites:
  - name: api
    run_list:
      - recipe[build-essential]
      - recipe[openstack-common]
      - recipe[openstack-common::client]
      - recipe[openstack-identity::openrc]
      - recipe[openstack-ops-database::server]
      - recipe[openstack-ops-database::openstack-db]
      - recipe[openstack-ops-messaging::rabbitmq-server]
      - recipe[openstack-identity::server-apache]
      - recipe[openstack-identity::registration]
      - recipe[openstack-container::api]
      - recipe[openstack-container::identity_registration]
  - name: common
    run_list:
      - recipe[openstack-common]
      - recipe[openstack-common::client]
      - recipe[openstack-identity::openrc]
      - recipe[openstack-container::common]
  - name: identity_registration
    run_list:
      - recipe[build-essential]
      - recipe[openstack-common]
      - recipe[openstack-common::client]
      - recipe[openstack-identity::openrc]
      - recipe[openstack-ops-database::server]
      - recipe[openstack-ops-database::openstack-db]
      - recipe[openstack-ops-messaging::rabbitmq-server]
      - recipe[openstack-identity::server-apache]
      - recipe[openstack-identity::registration]
      - recipe[openstack-container::identity_registration]
