name             'openstack-container'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
chef_version     '>= 12.18'
issues_url       'https://github.com/osuosl-cookbooks/openstack-container/issues'
source_url       'https://github.com/osuosl-cookbooks/openstack-container'
description      'Installs/Configures openstack-container'
version          '1.0.0'

supports         'centos', '~> 7.0'

depends 'apache2'
depends 'docker'
depends 'git'
depends 'openstackclient', '>= 19.0.0'
depends 'openstack-common', '>= 19.0.0'
depends 'openstack-dashboard', '>= 19.0.0'
depends 'openstack-identity', '>= 19.0.0'
depends 'sudo'
