default['openstack']['container']['user'] = 'zun'
default['openstack']['bind_service']['all']['container']['port'] = 9517
default['openstack']['bind_service']['all']['container']['host'] = '127.0.0.1'
default['openstack']['container']['group'] = 'zun'
default['openstack']['container']['virtualenv'] = '/opt/osc-zun'
default['openstack']['container']['release'] = 'stable/pike'
default['openstack']['container']['packages'] = %w(libffi-devel openssl-devel)
default['openstack']['container']['repository'] = 'https://git.openstack.org/openstack/zun.git'
%w(public internal admin).each do |ep_type|
  default['openstack']['endpoints'][ep_type]['container']['host'] = '127.0.0.1'
  default['openstack']['endpoints'][ep_type]['container']['scheme'] = 'http'
  default['openstack']['endpoints'][ep_type]['container']['path'] = '/v1/%(tenant_id)s'
  default['openstack']['endpoints'][ep_type]['container']['port'] = 9517
end
default['openstack']['container']['custom_template_banner'] = '
# This file is automatically generated by Chef
# Any changes will be overwritten
'
default['openstack']['container']['conf_dir'] = '/etc/zun'
default['openstack']['container']['conf_file'] =
  ::File.join(node['openstack']['container']['conf_dir'], 'zun.conf')
default['openstack']['container']['service_role'] = 'admin'
